#!/bin/sh
#
echo "Content-Type: multipart/x-mixed-replace; boundary=--boundary"
echo ""
while true
do
    echo "--boundary"
    echo "Content-Type: image/jpeg"
    echo ""
    /home/busybox/wget http://localhost:554/snapshot -O -
done
