#!/bin/sh
#
echo "Content-type: text/html"
echo ""
command=`echo "$QUERY_STRING" | awk '{split($0,array,"&")} END{print array[1]}' | awk '{split($0,array,"=")} END{print array[2]}'`
date=`date`
ipadd=`ip route get 1 | awk '{print $NF;exit}'`
uptime=`uptime`

if [ -f /home/HACKP ]; then
hacktype="PERSISTENT"
elif [ -f /home/HACKSD ]; then
hacktype="SD CARD"
fi


cat <<EOT
<!DOCTYPE html>
<html>
<head>
<title>Camera - WebUI</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {
    font-size: 100%;
    font-family: Arial, Verdana, sans-serif;
}
</style>
</head>
<body>
<div>
<button onclick="window.location.href='webui'" id="home">Home</button>
<br />
<br />
<button onclick="cmd('iron');" id="irledson">IR LEDs On</button>
<br />
<button onclick="cmd('iroff');" id="irledsoff">IR LEDs Off</button>
<br />
<br />

</div>
<table>
    <tr align="center">
        <td><button onclick="cmd('ptzlu');">&#11017;</button></td>
        <td><button onclick="cmd('ptzu');">&#11014;</button></td>
        <td><button onclick="cmd('ptzru');">&#11016;</button></td>
    </tr>
    <tr align="center">
        <td><button onclick="cmd('ptzl');">&#11013;</button></td>
        <td>PTZ</td>
        <td><button onclick="cmd('ptzr');">&#10145;</button></td>
    </tr>
    <tr align="center">
        <td><button onclick="cmd('ptzld');">&#11019;</button></td>
        <td><button onclick="cmd('ptzd');">&#11015;</button></td>
        <td><button onclick="cmd('ptzrd');">&#11018;</button></td>
    </tr>
</table>
<br />
Date - $date
<br />
IP Address - $ipadd
<br />
Uptime - $uptime
<br />
Hack Type - $hacktype
<br />
<a href="https://github.com/ant-thomas/zsgx1hacks" target="_blank">ZS-GX1 Hacks - Github</a>

<script>
function cmd(arg) {
var req = new XMLHttpRequest();
req.open("GET", "webui?command=" + arg, false);
req.send(null);
}
</script>

</body></html>
EOT

if [ -f /home/HACKP ]; then
ptzfolder="/home/hack"
elif [ -f /home/HACKSD ]; then
ptzfolder="/media/hack"
fi


 if [ "$command" = "iron" ]; then
  gio -s 46 1 > /dev/null
 fi
 if [ "$command" = "iroff" ]; then
  gio -s 46 0 > /dev/null
 fi
 if [ "$command" = "ptzu" ]; then
  $ptzfolder/ptz-ctrl u > /dev/null
 fi
 if [ "$command" = "ptzd" ]; then
  $ptzfolder/ptz-ctrl d > /dev/null
 fi
 if [ "$command" = "ptzl" ]; then
  $ptzfolder/ptz-ctrl l > /dev/null
 fi
 if [ "$command" = "ptzr" ]; then
  $ptzfolder/ptz-ctrl r > /dev/null
 fi
 if [ "$command" = "ptzlu" ]; then                                                           
  $ptzfolder/ptz-ctrl lu > /dev/null                                                         
 fi 
 if [ "$command" = "ptzld" ]; then                                                           
  $ptzfolder/ptz-ctrl ld > /dev/null                                                         
 fi 
 if [ "$command" = "ptzru" ]; then                                                           
  $ptzfolder/ptz-ctrl ru > /dev/null                                                         
 fi 
 if [ "$command" = "ptzrd" ]; then                                                           
  $ptzfolder/ptz-ctrl rd > /dev/null                                                         
 fi 
